pre_bump_hooks = []
post_bump_hooks = []

[commit_types]
dev = { changelog_title = "Development Changes" }
nit = { changelog_title = "Small Nitpicks" }

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]
