name: Tests

on:
  pull_request:
  push:
    branches:
      - senpai

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: 27.2
      - name: let her rippp
        run: emacs -batch -l ert -l arr-test.el -f ert-run-tests-batch-and-exit
