name: Tests

on:
  pull_request:
  push:
    paths-ignore:
      - '**.org'
      - 'LICENCE'
    branches:
      - senpai

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: Install emacs
        uses: purcell/setup-emacs@master
        with:
          version: 27.2
      - name: Run test suite
        run: emacs -batch -l ert -l arr-test.el -f ert-run-tests-batch-and-exit
